[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask==2.3.3",
    "google-generativeai==0.7.0",
    "werkzeug==2.3.7",
    "psycopg2-binary==2.9.7",
]
